// Generated by gen-extensions.ts from n8n-workflow 2.16.0. Do not edit.
import type { DateTime, DurationUnit } from 'luxon';

// Date extensions also apply to luxon DateTime (expression-extension.ts dispatches on isDateTime).
declare module 'luxon' {
	interface DateTime {
		beginningOf(unit?: DurationUnit): DateTime;
		endOfMonth(): DateTime;
		extract(unit?: string): number;
		isBetween(date1: string | DateTime, date2: string | DateTime): boolean;
		isDst(): boolean;
		isInLast(n: number, unit?: DurationUnit): boolean;
		isWeekend(): boolean;
		minus(n: number | object, unit?: string): DateTime;
		plus(n: number | object, unit?: string): DateTime;
		format(fmt: string): string;
		toDateTime(): DateTime;
		diffTo(otherDateTime: string | DateTime, unit: string | string[]): number | Record<DurationUnit, number>;
		diffToNow(unit: string | string[]): number | Record<DurationUnit, number>;
		toInt(): any;
		toFloat(): any;
		toBoolean(): any;
		isEmpty(): boolean;
		isNotEmpty(): boolean;
	}
}

declare global {
	interface String {
		hash(algo?: string): string;
		removeMarkdown(): string;
		removeTags(): string;
		toDate(): Date;
		toDateTime(format?: string): DateTime;
		toBoolean(): boolean;
		toDecimalNumber(): any;
		toNumber(): number;
		toFloat(): number;
		toInt(radix?: number): number;
		toWholeNumber(): any;
		toSentenceCase(): string;
		toSnakeCase(): string;
		toTitleCase(): string;
		urlDecode(allChars?: boolean): string;
		urlEncode(allChars?: boolean): string;
		quote(mark?: string): string;
		replaceSpecialChars(): string;
		length(): number;
		isDomain(): boolean;
		isEmail(): boolean;
		isNumeric(): boolean;
		isUrl(): boolean;
		isEmpty(): boolean;
		isNotEmpty(): boolean;
		toJsonString(): string;
		extractEmail(): string;
		extractDomain(): string;
		extractUrl(): string;
		extractUrlPath(): string;
		parseJson(): any;
		base64Encode(): string;
		base64Decode(): string;
	}
	interface Number {
		ceil(): number;
		floor(): number;
		format(locale?: string, options?: object): string;
		round(decimalPlaces?: number): number;
		abs(): number;
		isInteger(): boolean;
		isEven(): boolean;
		isOdd(): boolean;
		toBoolean(): boolean;
		toInt(): any;
		toFloat(): any;
		toDateTime(format?: string): DateTime;
	}
	interface Boolean {
		toBoolean(): any;
		toInt(): any;
		toFloat(): any;
		toNumber(): number;
		toDateTime(): any;
	}
	interface Array<T> {
		removeDuplicates(...fieldNames: any[]): T[];
		unique(...fieldNames: any[]): T[];
		first(): T;
		last(): T;
		pluck(...fieldNames: string[]): T[];
		randomItem(): T;
		sum(): number;
		min(): number;
		max(): number;
		average(): number;
		isNotEmpty(): boolean;
		isEmpty(): boolean;
		compact(): T[];
		smartJoin(keyField: string, nameField: string): Record<string, any>;
		chunk(length: number): T[];
		renameKeys(from: string, to: string): T[];
		merge(otherArray: T[]): Record<string, any>;
		union(otherArray: T[]): T[];
		difference(otherArray: T[]): T[];
		intersection(otherArray: T[]): T[];
		append(...elements: any[]): T[];
		toJsonString(): string;
		toInt(): any;
		toFloat(): any;
		toBoolean(): any;
		toDateTime(): any;
	}
	interface Object {
		isEmpty(): boolean;
		isNotEmpty(): boolean;
		hasField(name: string): boolean;
		removeField(key: string): Record<string, any>;
		removeFieldsContaining(value: string): Record<string, any>;
		keepFieldsContaining(value: string): Record<string, any>;
		compact(): Record<string, any>;
		urlEncode(): string;
		keys(): string[];
		values(): any[];
		toJsonString(): string;
		toInt(): any;
		toFloat(): any;
		toBoolean(): any;
		toDateTime(): any;
	}
	interface Date {
		beginningOf(unit?: DurationUnit): DateTime;
		endOfMonth(): DateTime;
		extract(unit?: string): number;
		isBetween(date1: string | DateTime, date2: string | DateTime): boolean;
		isDst(): boolean;
		isInLast(n: number, unit?: DurationUnit): boolean;
		isWeekend(): boolean;
		minus(n: number | object, unit?: string): DateTime;
		plus(n: number | object, unit?: string): DateTime;
		format(fmt: string): string;
		toDateTime(): DateTime;
		diffTo(otherDateTime: string | DateTime, unit: string | string[]): number | Record<DurationUnit, number>;
		diffToNow(unit: string | string[]): number | Record<DurationUnit, number>;
		toInt(): any;
		toFloat(): any;
		toBoolean(): any;
		isEmpty(): boolean;
		isNotEmpty(): boolean;
	}

	function $if<T, F = undefined>(condition: boolean, valueIfTrue: T, valueIfFalse?: F): T | F;
	function $min(...numbers: number[]): number;
	function $max(...numbers: number[]): number;
	function $average(...numbers: number[]): number;
	function $not(value: unknown): boolean;
	function $ifEmpty<V, E>(value: V, defaultValue: E): V | E;
}

export {};
