// Writes extensions.d.ts: n8n's expression extension methods as global interface
// augmentations, read from n8n-workflow's doc metadata. Re-run after bumping n8n-workflow.
import { writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import type { ExpressionExtensions as ExpressionExtensionsType } from 'n8n-workflow';

// n8n-workflow's ESM build trips on a named import from @n8n/tournament; use the CJS build.
const require = createRequire(import.meta.url);
const { ExpressionExtensions } = require('n8n-workflow/dist/cjs/extensions/index.js') as {
	ExpressionExtensions: typeof ExpressionExtensionsType;
};
const { extendedFunctions } = require('n8n-workflow/dist/cjs/extensions/extended-functions.js') as {
	extendedFunctions: Record<string, Function>;
};

type DocArg = { name: string; type?: string; optional?: boolean; variadic?: boolean };
type Doc = { name: string; returnType?: string; args?: DocArg[] };

// Doc type strings are informal; map the ones that occur to TS.
const docType = (t: string | undefined, self: string): string => {
	switch (t) {
		case undefined:
		case 'any':
			return 'any';
		case 'string':
		case 'number':
		case 'boolean':
		case 'object':
			return t;
		case 'Array':
			return self === 'Array' ? 'T[]' : 'any[]';
		case 'Object':
			return 'Record<string, any>';
		case 'DateTime':
		case 'Date':
			return t;
		case 'Function':
			return '(...args: any[]) => any';
		default:
			return /^[\w\s|<>,[\]]+$/.test(t) ? t : 'any';
	}
};

// Doc metadata says `any` where the real return is the element or key type.
const RETURN_OVERRIDES: Record<string, Record<string, string>> = {
	Array: { first: 'T', last: 'T', randomItem: 'T', unique: 'T[]', removeDuplicates: 'T[]', compact: 'T[]' },
	Object: { keys: 'string[]', values: 'any[]' },
};

const signature = (method: string, doc: Doc | undefined, self: string): string => {
	const args = (doc?.args ?? [])
		.map((a) => {
			const type = docType(a.type, self);
			return a.variadic ? `...${a.name}: ${type}[]` : `${a.name}${a.optional ? '?' : ''}: ${type}`;
		})
		.join(', ');
	const returnType = RETURN_OVERRIDES[self]?.[method] ?? docType(doc?.returnType, self);
	return `${method}(${args}): ${returnType};`;
};

const members = (typeName: string): string => {
	const map = ExpressionExtensions.find((m) => m.typeName === typeName);
	if (!map) return '';
	return Object.entries(map.functions)
		.map(([name, fn]) => `\t\t${signature(name, (fn as { doc?: Doc }).doc, typeName)}`)
		.join('\n');
};

// $if is rewritten by an AST hook in n8n and has no runtime doc; declared by hand.
const functions = Object.entries(extendedFunctions)
	.filter(([name]) => name.startsWith('$'))
	.map(([name, fn]) => {
		if (name === '$ifEmpty') return 'function $ifEmpty<V, E>(value: V, defaultValue: E): V | E;';
		if (name === '$not') return 'function $not(value: unknown): boolean;';
		const doc = (fn as { doc?: Doc }).doc ?? {
			name,
			returnType: 'number',
			args: [{ name: 'numbers', type: 'number', variadic: true }],
		};
		return `function ${signature(name, doc, 'root')}`;
	});

const out = `// Generated by gen-extensions.ts from n8n-workflow ${require('n8n-workflow/package.json').version}. Do not edit.
import type { DateTime, DurationUnit } from 'luxon';

// Date extensions also apply to luxon DateTime (expression-extension.ts dispatches on isDateTime).
declare module 'luxon' {
	interface DateTime {
${members('Date')}
	}
}

declare global {
	interface String {
${members('String')}
	}
	interface Number {
${members('Number')}
	}
	interface Boolean {
${members('Boolean')}
	}
	interface Array<T> {
${members('Array')}
	}
	interface Object {
${members('Object')}
	}
	interface Date {
${members('Date')}
	}

	function $if<T, F = undefined>(condition: boolean, valueIfTrue: T, valueIfFalse?: F): T | F;
	${functions.join('\n\t')}
}

export {};
`;

writeFileSync(new URL('./extensions.d.ts', import.meta.url), out);
console.log('wrote extensions.d.ts');
