packages:
  - packages/*
  - packages/@n8n/*
  - playground
onlyBuiltDependencies:
  - esbuild
ignoredBuiltDependencies:
  - isolated-vm
  - "@vscode/vsce-sign"
  - keytar
allowBuilds:
  '@biomejs/biome': true
  esbuild: true
  isolated-vm: true
