// Writes extensions.d.ts: n8n's expression extension methods as global interface
// augmentations, read from n8n-workflow's doc metadata. Re-run after bumping n8n-workflow.
import { writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';
import type { ExpressionExtensions as ExpressionExtensionsType } from 'n8n-workflow';

// n8n-workflow's ESM build trips on a named import from @n8n/tournament; use the CJS build.
const require = createRequire(import.meta.url);
const { ExpressionExtensions } = require('n8n-workflow/dist/cjs/extensions/index.js') as {
	ExpressionExtensions: typeof ExpressionExtensionsType;
};
const { extendedFunctions } = require('n8n-workflow/dist/cjs/extensions/extended-functions.js') as {
	extendedFunctions: Record<string, Function>;
};

type DocArg = { name: string; type?: string; optional?: boolean; variadic?: boolean; description?: string };
type Doc = {
	name: string;
	returnType?: string;
	args?: DocArg[];
	description?: string;
	examples?: Array<{ example: string; evaluated?: string; description?: string }>;
	docURL?: string;
	hidden?: boolean;
	aliases?: string[];
};

/** JSDoc from n8n's doc metadata, so hover and completion details carry the docs. */
const jsdoc = (method: string, doc: Doc | undefined, indent: string): string => {
	if (!doc) return '';
	const lines = [
		...(doc.description ? [doc.description] : []),
		...(doc.name !== method ? [`Alias of \`${doc.name}()\`.`] : []),
		...(doc.args ?? []).filter((a) => a.description).map((a) => `@param ${a.name} ${a.description}`),
		...(doc.examples ?? []).slice(0, 2).map((e) => `@example ${e.example}${e.evaluated ? ` // ${e.evaluated}` : ''}`),
		...(doc.docURL ? [`@see ${doc.docURL}`] : []),
	];
	if (lines.length === 0) return '';
	return `${indent}/**\n${lines.map((l) => `${indent} * ${l.replace(/\*\//g, '* /')}`).join('\n')}\n${indent} */\n`;
};

// Doc type strings are informal; map the ones that occur to TS.
const docType = (t: string | undefined, self: string): string => {
	switch (t) {
		case undefined:
		case 'any':
			return 'any';
		case 'string':
		case 'number':
		case 'boolean':
		case 'object':
			return t;
		case 'Array':
			return self === 'Array' ? 'T[]' : 'any[]';
		case 'Object':
			return 'Record<string, any>';
		case 'DateTime':
		case 'Date':
			return t;
		case 'Function':
			return '(...args: any[]) => any';
		default:
			return /^[\w\s|<>,[\]]+$/.test(t) ? t : 'any';
	}
};

// Doc metadata says `any` where the real return is the element or key type.
const RETURN_OVERRIDES: Record<string, Record<string, string>> = {
	Array: { first: 'T', last: 'T', randomItem: 'T', unique: 'T[]', removeDuplicates: 'T[]', compact: 'T[]' },
	Object: { keys: 'string[]', values: 'any[]' },
};

const signature = (method: string, doc: Doc | undefined, self: string): string => {
	const args = (doc?.args ?? [])
		.map((a) => {
			const type = docType(a.type, self);
			return a.variadic ? `...${a.name}: ${type}[]` : `${a.name}${a.optional ? '?' : ''}: ${type}`;
		})
		.join(', ');
	const returnType = RETURN_OVERRIDES[self]?.[method] ?? docType(doc?.returnType, self);
	return `${method}(${args}): ${returnType};`;
};

// n8n dispatches these at runtime, but as declarations they would collide with an existing
// property: Array#length from lib, DateTime#isWeekend from @types/luxon (a getter, not a method).
const COLLIDES: Record<string, string[]> = { String: ['length'], Array: ['length'], Date: ['isWeekend'] };

const members = (typeName: string): string => {
	const map = ExpressionExtensions.find((m) => m.typeName === typeName);
	if (!map) return '';
	return Object.entries(map.functions)
		.filter(([name]) => !COLLIDES[typeName]?.includes(name))
		.map(([name, fn]) => {
			const doc = (fn as { doc?: Doc }).doc;
			return `${jsdoc(name, doc, '\t\t')}\t\t${signature(name, doc, typeName)}`;
		})
		.join('\n');
};

// $if is rewritten by an AST hook in n8n and has no runtime doc; declared by hand.
const functions = Object.entries(extendedFunctions)
	.filter(([name]) => name.startsWith('$'))
	.map(([name, fn]) => {
		const doc = (fn as { doc?: Doc }).doc;
		const head = jsdoc(name, doc, '\t');
		if (name === '$ifEmpty') return `${head}\tfunction $ifEmpty<V, E>(value: V, defaultValue: E): V | E;`;
		if (name === '$not') return `${head}\tfunction $not(value: unknown): boolean;`;
		return `${head}\tfunction ${signature(name, doc ?? { name, returnType: 'number', args: [{ name: 'numbers', type: 'number', variadic: true }] }, 'root')}`;
	});

const out = `// Generated by gen-extensions.ts from n8n-workflow ${require('n8n-workflow/package.json').version}. Do not edit.
import type { DateTime, DurationUnit } from 'luxon';

// Date extensions also apply to luxon DateTime (expression-extension.ts dispatches on isDateTime).
declare module 'luxon' {
	interface DateTime {
${members('Date')}
	}
}

declare global {
	interface String {
${members('String')}
	}
	interface Number {
${members('Number')}
	}
	interface Boolean {
${members('Boolean')}
	}
	interface Array<T> {
${members('Array')}
	}
	interface Object {
${members('Object')}
	}
	interface Date {
${members('Date')}
	}

	/**
	 * Returns valueIfTrue when the condition holds, else valueIfFalse.
	 * @example $if($json.age >= 18, 'adult', 'minor')
	 * @see https://docs.n8n.io/code/builtin/convenience/
	 */
	function $if<T, F = undefined>(condition: boolean, valueIfTrue: T, valueIfFalse?: F): T | F;
${functions.join('\n')}
}

export {};
`;

const outPath = new URL('./extensions.d.ts', import.meta.url);
writeFileSync(outPath, out);
console.log('wrote extensions.d.ts');

// skipLibCheck hides duplicate-identifier clashes with lib or @types/luxon; check them here.
const dir = path.dirname(fileURLToPath(outPath));
const program = ts.createProgram([path.join(dir, 'extensions.d.ts'), path.join(dir, 'shapes.d.ts')], {
	strict: true,
	target: ts.ScriptTarget.ESNext,
	lib: ['lib.es2023.d.ts'],
	module: ts.ModuleKind.ESNext,
	moduleResolution: ts.ModuleResolutionKind.Bundler,
	types: [],
	noEmit: true,
	skipLibCheck: false,
});
const clashes = ts.getPreEmitDiagnostics(program).filter((d) => d.code === 2300);
for (const d of clashes) {
	const { line } = d.file!.getLineAndCharacterOfPosition(d.start!);
	console.error(`${path.relative(process.cwd(), d.file!.fileName)}:${line + 1}: ${ts.flattenDiagnosticMessageText(d.messageText, ' ')}`);
}
if (clashes.length) process.exit(1);
