// Generated from expr() and resolve() sites. Do not edit.
declare global {
	interface N8nResolvedTypes {
		"httpPagination::={{ $response.body.next ?? $request.url }}": { loose: any; strict: [] };
		"httpPagination::={{ $response.body.next }}": { loose: any; strict: [[{ readonly context: "httpPagination"; readonly response: { readonly next: "https://example.com?page=2"; readonly items: [1, 2]; }; readonly input: { readonly json: { readonly test: "hello"; readonly n: 3; readonly tags: ["a", "b"]; readonly user: { readonly name: "Ada"; readonly emails: ["ada@example.com"]; }; readonly nothing: null; }; readonly binaryKeys: readonly ["data"]; }; readonly nodes: { readonly Webhook: { readonly json: { readonly headers: { readonly host: "x"; }; readonly body: { readonly orderId: 42; }; }; readonly params: { readonly path: "orders"; readonly httpMethod: "POST"; }; }; readonly 'Edit Fields': { readonly json: { readonly total: 9.5; }; readonly binaryKeys: readonly ["invoice"]; }; }; readonly parameters: { readonly url: "https://example.com"; readonly options: { readonly timeout: 3000; }; }; readonly vars: readonly ["apiKey", "region"]; }, string], [{ context: "httpPagination"; response: { items: number[]; }; }, N8nResolveError], [{ response: { items: never[]; }; context: "httpPagination"; input: { readonly json: { readonly test: "hello"; readonly n: 3; readonly tags: ["a", "b"]; readonly user: { readonly name: "Ada"; readonly emails: ["ada@example.com"]; }; readonly nothing: null; }; readonly binaryKeys: readonly ["data"]; }; nodes: { readonly Webhook: { readonly json: { readonly headers: { readonly host: "x"; }; readonly body: { readonly orderId: 42; }; }; readonly params: { readonly path: "orders"; readonly httpMethod: "POST"; }; }; readonly 'Edit Fields': { readonly json: { readonly total: 9.5; }; readonly binaryKeys: readonly ["invoice"]; }; }; parameters: { readonly url: "https://example.com"; readonly options: { readonly timeout: 3000; }; }; vars: readonly ["apiKey", "region"]; }, N8nResolveError]] };
		"nodeParameter::={{ $('Webhook').item.json.body.orderId }}": { loose: any; strict: [[{ readonly input: { readonly json: { readonly test: "hello"; readonly n: 3; readonly tags: ["a", "b"]; readonly user: { readonly name: "Ada"; readonly emails: ["ada@example.com"]; }; readonly nothing: null; }; readonly binaryKeys: readonly ["data"]; }; readonly nodes: { readonly Webhook: { readonly json: { readonly headers: { readonly host: "x"; }; readonly body: { readonly orderId: 42; }; }; readonly params: { readonly path: "orders"; readonly httpMethod: "POST"; }; }; readonly 'Edit Fields': { readonly json: { readonly total: 9.5; }; readonly binaryKeys: readonly ["invoice"]; }; }; readonly parameters: { readonly url: "https://example.com"; readonly options: { readonly timeout: 3000; }; }; readonly vars: readonly ["apiKey", "region"]; }, number]] };
		"nodeParameter::={{ $input.all().map((i) => i.json.n).sum() }}": { loose: number; strict: [[{ readonly input: { readonly json: { readonly test: "hello"; readonly n: 3; readonly tags: ["a", "b"]; readonly user: { readonly name: "Ada"; readonly emails: ["ada@example.com"]; }; readonly nothing: null; }; readonly binaryKeys: readonly ["data"]; }; readonly nodes: { readonly Webhook: { readonly json: { readonly headers: { readonly host: "x"; }; readonly body: { readonly orderId: 42; }; }; readonly params: { readonly path: "orders"; readonly httpMethod: "POST"; }; }; readonly 'Edit Fields': { readonly json: { readonly total: 9.5; }; readonly binaryKeys: readonly ["invoice"]; }; }; readonly parameters: { readonly url: "https://example.com"; readonly options: { readonly timeout: 3000; }; }; readonly vars: readonly ["apiKey", "region"]; }, number]] };
		"nodeParameter::={{ $json.nothing.x }}": { loose: any; strict: [[{ readonly input: { readonly json: { readonly test: "hello"; readonly n: 3; readonly tags: ["a", "b"]; readonly user: { readonly name: "Ada"; readonly emails: ["ada@example.com"]; }; readonly nothing: null; }; readonly binaryKeys: readonly ["data"]; }; readonly nodes: { readonly Webhook: { readonly json: { readonly headers: { readonly host: "x"; }; readonly body: { readonly orderId: 42; }; }; readonly params: { readonly path: "orders"; readonly httpMethod: "POST"; }; }; readonly 'Edit Fields': { readonly json: { readonly total: 9.5; }; readonly binaryKeys: readonly ["invoice"]; }; }; readonly parameters: { readonly url: "https://example.com"; readonly options: { readonly timeout: 3000; }; }; readonly vars: readonly ["apiKey", "region"]; }, N8nResolveError]] };
		"nodeParameter::={{ $json.test.toTitleCase() }}": { loose: any; strict: [[{ readonly input: { readonly json: { readonly test: "hello"; readonly n: 3; readonly tags: ["a", "b"]; readonly user: { readonly name: "Ada"; readonly emails: ["ada@example.com"]; }; readonly nothing: null; }; readonly binaryKeys: readonly ["data"]; }; readonly nodes: { readonly Webhook: { readonly json: { readonly headers: { readonly host: "x"; }; readonly body: { readonly orderId: 42; }; }; readonly params: { readonly path: "orders"; readonly httpMethod: "POST"; }; }; readonly 'Edit Fields': { readonly json: { readonly total: 9.5; }; readonly binaryKeys: readonly ["invoice"]; }; }; readonly parameters: { readonly url: "https://example.com"; readonly options: { readonly timeout: 3000; }; }; readonly vars: readonly ["apiKey", "region"]; }, string]] };
		"nodeParameter::={{ $json.test.toUppercase() }}": { loose: any; strict: [[{ readonly input: { readonly json: { readonly test: "hello"; readonly n: 3; readonly tags: ["a", "b"]; readonly user: { readonly name: "Ada"; readonly emails: ["ada@example.com"]; }; readonly nothing: null; }; readonly binaryKeys: readonly ["data"]; }; readonly nodes: { readonly Webhook: { readonly json: { readonly headers: { readonly host: "x"; }; readonly body: { readonly orderId: 42; }; }; readonly params: { readonly path: "orders"; readonly httpMethod: "POST"; }; }; readonly 'Edit Fields': { readonly json: { readonly total: 9.5; }; readonly binaryKeys: readonly ["invoice"]; }; }; readonly parameters: { readonly url: "https://example.com"; readonly options: { readonly timeout: 3000; }; }; readonly vars: readonly ["apiKey", "region"]; }, N8nResolveError]] };
		"nodeParameter::={{ $json.whatever.you.like.toTitleCase() }}": { loose: any; strict: [] };
		"nodeParameter::={{ $now.toISO() }}": { loose: string | null; strict: [] };
		"nodeParameter::={{ $pageCount }}": { loose: N8nInvalidExpression; strict: [[{ readonly input: { readonly json: { readonly test: "hello"; readonly n: 3; readonly tags: ["a", "b"]; readonly user: { readonly name: "Ada"; readonly emails: ["ada@example.com"]; }; readonly nothing: null; }; readonly binaryKeys: readonly ["data"]; }; readonly nodes: { readonly Webhook: { readonly json: { readonly headers: { readonly host: "x"; }; readonly body: { readonly orderId: 42; }; }; readonly params: { readonly path: "orders"; readonly httpMethod: "POST"; }; }; readonly 'Edit Fields': { readonly json: { readonly total: 9.5; }; readonly binaryKeys: readonly ["invoice"]; }; }; readonly parameters: { readonly url: "https://example.com"; readonly options: { readonly timeout: 3000; }; }; readonly vars: readonly ["apiKey", "region"]; }, N8nInvalidExpression]] };
		"nodeParameter::=Order {{ $json.n }} for {{ $json.user.name }}": { loose: string; strict: [[{ readonly input: { readonly json: { readonly test: "hello"; readonly n: 3; readonly tags: ["a", "b"]; readonly user: { readonly name: "Ada"; readonly emails: ["ada@example.com"]; }; readonly nothing: null; }; readonly binaryKeys: readonly ["data"]; }; readonly nodes: { readonly Webhook: { readonly json: { readonly headers: { readonly host: "x"; }; readonly body: { readonly orderId: 42; }; }; readonly params: { readonly path: "orders"; readonly httpMethod: "POST"; }; }; readonly 'Edit Fields': { readonly json: { readonly total: 9.5; }; readonly binaryKeys: readonly ["invoice"]; }; }; readonly parameters: { readonly url: "https://example.com"; readonly options: { readonly timeout: 3000; }; }; readonly vars: readonly ["apiKey", "region"]; }, string]] };
	}
}
export {};
